# Linear model of coaptation line length

## Unadjusted

```{r}
M <- 
  df %>%
  select(matches("^type|Scaled|^radial$")) %>% 
  lm(radial ~ type, data = .)
M %>% glance %>% kable
M %>% tidy %>% kable(digits = c(0, 2, 2, 2, 4))
new <- data.frame(type = df$type %>% factor %>% levels)
merge(new %>% bind_cols(., predict(M, ., interval = "confidence") %>% data.frame),
      new %>% bind_cols(., predict(M, ., interval = "prediction") %>% data.frame),
      by = c("type", "fit")) %>% 
  rename(lowerConf = lwr.x,
         upperConf = upr.x,
         lowerPred = lwr.y,
         upperPred = upr.y) %>% 
  kable(digits = 2)
```

## Adjusted for body surface area

```{r}
M <- 
  df %>%
  select(matches("^type|Scaled|^radial$")) %>% 
  lm(radial ~ type + bsaScaled, data = .)
M %>% glance %>% kable
M %>% tidy %>% kable(digits = c(0, 2, 2, 2, 4))
new <- data.frame(type = rep(df$type %>% factor %>% levels, 3),
                  bsaScaled = rep(-1:1, each = 2),
                  scaling = rep(c("-1 SD from mean BSA",
                                  "Mean BSA",
                                  "+1 SD from mean BSA"), each = 2))
merge(new %>% bind_cols(., predict(M, ., interval = "confidence") %>% data.frame),
      new %>% bind_cols(., predict(M, ., interval = "prediction") %>% data.frame),
      by = c("type", "bsaScaled", "scaling", "fit")) %>% 
  rename(lowerConf = lwr.x,
         upperConf = upr.x,
         lowerPred = lwr.y,
         upperPred = upr.y) %>% 
  kable(digits = 2)
```

## Adjusted for orifice area

```{r}
M <- 
  df %>%
  lm(radial ~ type + orificeAreaScaled, data = .)
M %>% glance %>% kable
M %>% tidy %>% kable(digits = c(0, 2, 2, 2, 4))
new <- data.frame(type = rep(df$type %>% factor %>% levels, 3),
                  orificeAreaScaled = rep(-1:1, each = 2),
                  scaling = rep(c("-1 SD from mean orifice area",
                                  "Mean orifice area",
                                  "+1 SD from mean orifice area"), each = 2))
merge(new %>% bind_cols(., predict(M, ., interval = "confidence") %>% data.frame),
      new %>% bind_cols(., predict(M, ., interval = "prediction") %>% data.frame),
      by = c("type", "orificeAreaScaled", "scaling", "fit")) %>% 
  rename(lowerConf = lwr.x,
         upperConf = upr.x,
         lowerPred = lwr.y,
         upperPred = upr.y) %>% 
  kable(digits = 2)
```
